Feature 190224 sj home
marmetodevelopers/park-avenue pull request #3
Opened 2024-02-20 10:56 UTC by MTechSanjeev

### Problem
- Homepage

Monday Card Link: - https://marmeto-force.monday.com/boards/5752050817?userId=55682957

### Solution
- Image text carousel created

### Impacted Areas
- homepage

### Done Checklist
- [x] Performed unit testing to ensure functionality and identify potential issues.
- [x] Followed basic code standards and best practices. (indentation, media queries, basic customizer things)
- [x] Added comments to explain complex logic or improve code readability.
- [x] Followed Naming conventions and proper variable declaration.
- [x] Handled edge cases and errors gracefully to prevent crashes.
- [x] Optimized the code for production to ensure performance.
Please review this PR and provide feedback. Thank you!

2024-02-26 10:21 UTC, Manuraj-Marmeto requested changes

2024-02-26 10:21 UTC, Manuraj-Marmeto commented on layout/theme.liquid
> +    <script src="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/js/splide.min.js"></script>
Remove the cdn link for splide and download the splide js file and add it in the asset folder and pull it from assest folder here

2024-02-26 10:21 UTC, Manuraj-Marmeto commented on layout/theme.liquid
> +    <link href="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/css/splide.min.css" rel="stylesheet">
Remove the cdn link for splide and download the splide css file and add it in the asset folder and pull it from assest folder here

2024-02-26 10:35 UTC, hatprabMarmeto requested changes
Hi @MTechSanjeev 
Please check the comment on the code. Please fix the changes. Or do let us know if there is any other reason for doing that task

2024-02-26 10:35 UTC, hatprabMarmeto commented on assets/custom.css
> +	position: initial;
Is this code required @MTechSanjeev

2024-02-26 10:35 UTC, hatprabMarmeto commented on assets/custom.css
> +button.splide__pagination__page.ibc_page {
CSS selector can be improved 
from 
`button.splide__pagination__page.ibc_page`
to
`.splide__pagination__page.ibc_page`

2024-02-26 10:35 UTC, hatprabMarmeto commented on assets/custom.css
> +	background: linear-gradient(90deg, rgba(0, 0, 0, 1) 60%, rgba(255, 255, 255, 1) 60%) !important;
Can you explain the logic behind adding the important attribute ?

2024-02-26 10:35 UTC, hatprabMarmeto commented on assets/custom.css
> +	margin: 0px auto !important;
Can you explain the logic behind adding the important attribute ?

2024-02-26 10:35 UTC, hatprabMarmeto commented on assets/custom.css
> +	button.splide__pagination__page.ibc_page {
The code can be updated from
`button.splide__pagination__page.ibc_page`
to
`.splide__pagination__page.ibc_page`

2024-02-26 10:35 UTC, hatprabMarmeto commented on assets/home-custom.css
> +.title {
Too open css. 
.title is global and can be added to multiple different component. Avoid using this name when using the CSS file globally.

Prefix or Sufix it with the parent page class.
If you want the design to follow only one specific page.

2024-02-26 10:35 UTC, hatprabMarmeto commented on assets/home-custom.css
> +    padding: 0 !important;
!important should be avoided

2024-02-26 10:35 UTC, hatprabMarmeto commented on assets/home-custom.css
> +    display: block !important;
Writing !important should be avoided

2024-02-26 10:35 UTC, hatprabMarmeto commented on assets/home-custom.css
> +    padding: 0rem !important;
Writing !important should be avoided

2024-02-26 10:35 UTC, hatprabMarmeto commented on assets/home-custom.css
> +        padding: 0rem !important;
Writing !important should be avoided

2024-02-26 10:35 UTC, hatprabMarmeto commented on assets/home-custom.css
> +    margin-top: -16px;
Try to replace the code with better css rule as negative margin is not good to use

2024-02-26 10:35 UTC, hatprabMarmeto commented on assets/home-custom.css
> +    padding: 0rem !important;
Writing !important should be avoided

2024-02-26 10:35 UTC, hatprabMarmeto commented on layout/theme.liquid
> +    <link href="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/css/splide.min.css" rel="stylesheet">
As Suggested move the file to asset and then load for better website performance.
As it will uploaded to shopify and make it faster to load.

2024-02-26 10:35 UTC, hatprabMarmeto commented on sections/park-trending-carousel.liquid
> +  document.addEventListener('DOMContentLoaded', () => {
Add a single common JS which can handle all the sliders at onec

2024-02-26 11:35 UTC, MTechSanjeev commented on layout/theme.liquid
> +    <script src="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/js/splide.min.js"></script>
Remove the cdn link for splide and download the splide js file and add it in the asset folder and pull it from assest folder here >>>>>>>>> splide.js file and splide.css file added to the assets

2024-02-26 11:35 UTC, MTechSanjeev commented on layout/theme.liquid
> +    <link href="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/css/splide.min.css" rel="stylesheet">
Remove the cdn link for splide and download the splide js file and add it in the asset folder and pull it from assest folder here >>>>>>>>> splide.js file and splide.css file added to the assets

2024-02-26 11:45 UTC, MTechSanjeev commented on layout/theme.liquid
> +    <link href="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/css/splide.min.css" rel="stylesheet">
As Suggested move the file to asset and then load for better website performance.
As it will uploaded to shopify and make it faster to load. >>>>>>>> added two files to assets splide.js and spilde.css

2024-02-26 13:02 UTC, MTechSanjeev commented on assets/custom.css
> +	position: initial;
Is this code required >>>>>> yes it's required to make pagination make pagination dots below the slide carousel container

2024-02-26 13:04 UTC, MTechSanjeev commented on assets/custom.css
> +button.splide__pagination__page.ibc_page {
Done

2024-02-26 13:08 UTC, MTechSanjeev commented on layout/theme.liquid
> +    <link href="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/css/splide.min.css" rel="stylesheet">
Done

2024-02-26 13:08 UTC, MTechSanjeev commented on assets/custom.css
> +	margin: 0px auto !important;
removed

2024-02-26 13:08 UTC, MTechSanjeev commented on assets/custom.css
> +	button.splide__pagination__page.ibc_page {
Done

2024-02-26 13:28 UTC, MTechSanjeev commented on assets/home-custom.css
> +        padding: 0rem !important;
Without !important i didn't get desired output so i used !important

2024-02-26 13:33 UTC, MTechSanjeev commented on assets/home-custom.css
> +    padding: 0rem !important;
It will not work without !important so i used

2024-02-27 04:48 UTC, MTechSanjeev commented on sections/park-trending-carousel.liquid
> +  document.addEventListener('DOMContentLoaded', () => {
Add a single common JS which can handle all the sliders at onec >>>>>>>>> custom-park-sanjeev.js to inplement the all the sliders js

2024-02-27 05:44 UTC, MTechSanjeev commented on assets/home-custom.css
> +    margin-top: -16px;
Try to replace the code with better css rule as negative margin is not good to use >>>>>>>>>  removed the negative margin

2024-02-27 11:06 UTC, hatprabMarmeto requested changes
There are still pending pointer which are left please do check once

2024-02-28 05:10 UTC, MTechSanjeev commented on assets/custom-park-sanjeev.js
> +        debugger
Remove Debugger form the code. >>>>>>>>>> debugger removed

2024-02-28 05:13 UTC, MTechSanjeev commented on assets/custom-park-sanjeev.js
Don't use you name in the file names. >>>>>>>> replace cutom-park-sanjeev.js with custom-park.js

2024-02-28 05:39 UTC, MTechSanjeev commented on assets/home-custom.css
> +.title {
Prefix or Sufix it with the parent page class. >>>>>>>> added parent class as prefix to the target element

2024-02-28 05:46 UTC, MTechSanjeev commented on assets/home-custom.css
> +    padding: 0rem !important;
to the remove the splide padding important is required

2024-02-28 06:08 UTC, MTechSanjeev commented on assets/home-custom.css
> +    padding: 0 !important;
!important should be avoided>>>>>>>> To override the splide default style important required

2024-02-28 06:10 UTC, MTechSanjeev commented on assets/home-custom.css
> +    display: block !important;
Writing !important should be avoided >>>>>>>> this is the default style of base css for empty div display none so to make it display block it's required

2024-02-28 06:17 UTC, MTechSanjeev commented on assets/home-custom.css
> +    padding: 0rem !important;
To override the splide style !important required

2024-02-28 07:35 UTC, merged