Feature 22224 sp blogpage
marmetodevelopers/park-avenue pull request #4
Opened 2024-02-27 11:38 UTC by shibasundar-marmeto

Pull Request (PR) Request Template:

### Problem
 blog listing page and articlePage

Monday Card Link: [https://marmeto-force.monday.com/boards/5752050817?userId=54242963]
preview : https://parkavenue-india.myshopify.com/blogs/all-blogs?preview_theme_id=165404442904

### Solution
blog page and article page created  

### Impacted Areas
blog page and article page

### Done Checklist
- [x] Performed unit testing to ensure functionality and identify potential issues.
- [x] Followed basic code standards and best practices. (indentation, media queries, basic customizer things)
- [x] Added comments to explain complex logic or improve code readability.
- [x] Followed Naming conventions and proper variable declaration.
- [x] Handled edge cases and errors gracefully to prevent crashes.
- [x] Optimized the code for production to ensure performance.

Please review this PR and provide feedback. Thank you!

2024-02-28 10:38 UTC, hatprabMarmeto requested changes
@shibasundar-marmeto 
Please check the comments 

Also please fix the fonts and design as it does't match what is in the figma.

2024-02-28 10:38 UTC, hatprabMarmeto commented on assets/custom-article.css
> +  color: #231f20;
A good practice is to have to color define globally for the text so it save CSS file length. And where we need to override/change the color to something different there only we should be changing it.

2024-02-28 10:38 UTC, hatprabMarmeto commented on assets/custom-article.css
> +  color: #231f20;
Make color Globally for all the common tags such as 
h1,h2,p, a , etc .

2024-02-28 10:38 UTC, hatprabMarmeto commented on assets/custom-blog.css
> +.recent-article-image-container img {
Image are getting stretched please fix it.

2024-02-28 10:38 UTC, hatprabMarmeto commented on assets/custom-blog.css
> +}
All of these are common and can be grouped together

2024-02-28 10:38 UTC, hatprabMarmeto commented on assets/custom-blog.css
> +  letter-spacing: -0.2px;
Font Should have been picked from global class

2024-02-28 10:38 UTC, hatprabMarmeto commented on assets/custom-blog.css
> +  letter-spacing: 1px;
Should have been a common class that we could use multiple places

2024-02-28 10:38 UTC, hatprabMarmeto commented on assets/custom-blog.css
> +  }
What is the purpose of
`.item:nth-child(n)`

2024-02-28 10:38 UTC, hatprabMarmeto commented on assets/custom-blog.css
> +  }
Suggestion: the padding can be written in short hand 
`padding: 0 1.7rem 0 1.7rem; `
can be written as 
`padding: 0 1.7rem;`

2024-02-28 10:38 UTC, hatprabMarmeto commented on sections/main-blog.liquid
>  {{ 'component-card.css' | asset_url | stylesheet_tag }}
Are this required ?

2024-02-28 10:38 UTC, hatprabMarmeto commented on sections/main-blog.liquid
>  {{ 'component-article-card.css' | asset_url | stylesheet_tag }}
Is this required ?

2024-02-29 05:32 UTC, shibasundar-marmeto commented on assets/custom-article.css
> +  color: #231f20;
this color is for only content inside articles it is used only one time

2024-02-29 05:45 UTC, shibasundar-marmeto commented on assets/custom-blog.css
> +}
fixed

2024-02-29 05:46 UTC, shibasundar-marmeto commented on assets/custom-blog.css
> +  letter-spacing: -0.2px;
fixed

2024-02-29 05:48 UTC, shibasundar-marmeto commented on assets/custom-blog.css
> +  }
fixed

2024-03-05 06:46 UTC, S-Darshan commented
Closing PR reason: new PR will be opened with UT changes.

2024-03-05 06:46 UTC, closed without merging