Bugs 160324 vk home collection page rework
marmetodevelopers/park-avenue pull request #46
Opened 2024-03-19 06:37 UTC by VijayMarmetian

Pull Request (PR) Request Template:

### Problem
To built a brand collection page and modify the home page design 

Monday Card Link: 
https://marmeto-force.monday.com/boards/5752050817/pulses/6271459014

### Solution
Built a new section and modified existing sections for homepage and collection page.

<Visual representation or screenshots>

### Impacted Areas
<Explain other areas of the application that could be affected by this change.>

###Preview link with store password
https://parkavenue-india.myshopify.com/?preview_theme_id=166093488408
https://parkavenue-india.myshopify.com/pages/collections?preview_theme_id=166093488408
marmeto

### Done Checklist
- [x] Performed unit testing to ensure functionality and identify potential issues.
- [x] Followed basic code standards and best practices. (indentation, media queries, basic customizer things)
- [x] Added comments to explain complex logic or improve code readability.
- [x] Followed Naming conventions and proper variable declaration.
- [x] Handled edge cases and errors gracefully to prevent crashes.
- [x] Optimized the code for production to ensure performance.

Please review this PR and provide feedback. Thank you!

2024-03-19 11:06 UTC, arshiya-khanam requested changes

2024-03-19 11:06 UTC, arshiya-khanam commented on sections/brand-collection.liquid
> +              "id": "image_small"
add recommended size

2024-03-19 11:06 UTC, arshiya-khanam commented on sections/brand-collection.liquid
> +              "id": "image_desktop"
add recommended size

2024-03-19 11:06 UTC, arshiya-khanam commented on sections/contact-image-banner.liquid
> +        <span class="h2"> HOW CAN WE HELP ?</span>
do not hard code

2024-03-19 11:06 UTC, arshiya-khanam commented on sections/image-banner-carousel.liquid
>              "id": "image_desktop"
add recommended size

2024-03-19 11:06 UTC, arshiya-khanam commented on sections/video-section.liquid
> +          "label": "t:sections.video.settings.cover_image.label"
add recommended size

2024-03-21 12:20 UTC, Manuraj-Marmeto requested changes

2024-03-21 12:20 UTC, Manuraj-Marmeto commented on assets/custom.css
> +	position: absolute;
the intentation is bad here 
Please make it aligned

2024-03-29 07:49 UTC, merged